config/routes.rb
MotCache::Application.routes.draw do |map|
  resources :grilles

  resources :lexiques
  map.resources :grilles, :member => { :confirm_destroy => :get }

end

app/models/lexique.rb
class Lexique < ActiveRecord::Base

  before_save :init_lenght
  
  def init_lenght
    self.nbr_lettre = self.mot.length
  end

  def self.search(search, page)
    paginate :per_page => 5, :page => page,
             :conditions => ['mot like ?', "%#{search}%"], :order => 'mot'
  end

  def self.obtenir_liste_mot(ids)
    liste = []
    lexiques = Lexique.find(:all, :conditions => "id in (#{ids})", :order => "mot asc")
    lexiques.each {|lexique| liste << lexique.mot}
    liste
  end
end

app/controllers/lexiques_controller.rb
class LexiquesController < ApplicationController
  # GET /lexiques
  # GET /lexiques.xml
  def index
    @lexiques = Lexique.paginate(:per_page => 20, :page => params[:page], :order => "mot asc")
  end

  # GET /lexiques/1
  # GET /lexiques/1.xml
  def show
    @lexique = Lexique.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lexique }
    end
  end

  # GET /lexiques/new
  # GET /lexiques/new.xml
  def new
    @lexique = Lexique.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lexique }
    end
  end

  # GET /lexiques/1/edit
  def edit
    @lexique = Lexique.find(params[:id])
  end

  # POST /lexiques
  # POST /lexiques.xml
  def create
    @lexique = Lexique.new(params[:lexique])
    respond_to do |format|
      if @lexique.save
        format.html { redirect_to(@lexique, :notice => 'Lexique was successfully created.') }
        format.xml  { render :xml => @lexique, :status => :created, :location => @lexique }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lexique.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lexiques/1
  # PUT /lexiques/1.xml
  def update
    @lexique = Lexique.find(params[:id])

    respond_to do |format|
      if @lexique.update_attributes(params[:lexique])
        format.html { redirect_to(@lexique, :notice => 'Lexique was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lexique.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lexiques/1
  # DELETE /lexiques/1.xml
  def destroy
    @lexique = Lexique.find(params[:id])
    @lexique.destroy

    respond_to do |format|
      format.html { redirect_to(lexiques_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lexiques_helper.rb
module LexiquesHelper
end

app/views/lexiques/_form.html.erb
<%= form_for(@lexique) do |f| %>
  <% if @lexique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lexique.errors.count, "error") %> prohibited this lexique from being saved:</h2>

      <ul>
      <% @lexique.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mot %><br />
    <%= f.text_field :mot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lexiques/_lexiques.html.erb
<%= will_paginate @lexiques %>

<% for lexique in @lexiques %>
    <div class="lexique">
      <h3>
        <%= link_to h(lexique.mot), lexique %>
      </h3>
      <div class="actions">
        <%= link_to 'Edit', edit_lexique_path(lexique) %>
        <%= link_to 'Destroy', lexique, :method => :delete %>
      </div>
    </div>
<% end %>
<%= will_paginate @lexiques %>

app/views/lexiques/edit.html.erb
<h1>Editing lexique</h1>

<%= render 'form' %>

<%= link_to 'Show', @lexique %> |
<%= link_to 'Back', lexiques_path %>

app/views/lexiques/index.html.erb
<h1>Listing lexiques</h1>
<% javascript "pagination" %>

<div id="lexiques">
  <%= render 'lexiques' %>
</div>

<p><%= link_to 'New Lexique', new_lexique_path %></p>

app/views/lexiques/index.js.erb
//alert("ceci est une demande ajax!");
$("#lexiques").html("<%= escape_javascript(render("lexiques"))%>");
// #lexiques est le div

app/views/lexiques/new.html.erb
<h1>New lexique</h1>

<%= render 'form' %>

<%= link_to 'Back', lexiques_path %>

app/views/lexiques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mot:</b>
  <%= @lexique.mot %>
</p>

<p>
  <b>Nbr lettre:</b>
  <%= @lexique.nbr_lettre %>
</p>


<%= link_to 'Edit', edit_lexique_path(@lexique) %> |
<%= link_to 'Back', lexiques_path %> |
<%= link_to 'New Lexique', new_lexique_path %>